services:
  - type: web
    name: wplay-teste-4h
    runtime: python
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --threads 8 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TMDB_BEARER_TOKEN
        value: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmMGU2ZDExZDllZTg3N2ViZTgyNTFiYmJiMzE3OGI1NSIsIm5iZiI6MTc3OTQwOTk0Mi4wODgsInN1YiI6IjZhMGZhNDE2MTZjNmUzYmIyMTIzNGZmNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.C2DLCX9AxO1MjTHlEXTJBGgMwZHEgDpFoT7ARGRSZLg
      - key: TMDB_API_KEY
        value: f0e6d11d9ee877ebe8251bbbb3178b55
      - key: MC_USERNAME
        sync: false
      - key: MC_PASSWORD
        sync: false
      - key: SUPABASE_DB_PASSWORD
        sync: false
      - key: SUPABASE_PROJECT_REF
        sync: false
      - key: SUPABASE_PROJECT_REGION
        sync: false
      - key: SUPABASE_DB_HOST
        sync: false
      - key: SUPABASE_DB_PORT
        sync: false
      - key: SUPABASE_DB_USER
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_DB_URL
        sync: false
      - key: KIRVANO_WEBHOOK_TOKEN
        sync: false
